var testData = {    
                    "data": {
                        "total": "1",
                        "wait_for_accept": 1,
                        "unread_update": 0,
                        "postpone": 1,
                        "refuse": 0,
                         "data": [{                
                            "id": "1",
                            "number": "OM 1",
                            "description": "公司内网频繁报恶意，怀疑是误报",
                            "status": "1",
                            "type": "3",
                            "close": "1",
                            "refuse": "0",
                            "addtime": "2017-06-22 15:51:32",
                            "updatetime": "2017-06-13 11:49:54",
                            "donetime": "2017-06-13 14:22:49",
                            "predict_delivery_time": "2017-06-13 11:39:17",
                            "actual_delivery_time": "2017-06-13 14:16:06"            
                        },
                        {                
                            "id": "2",
                            "number": "OM 2",
                            "description": "公司内网频繁报恶意，怀疑是误报",
                            "status": "2",
                            "type": "3",
                            "close": "1",
                            "refuse": "0",
                            "addtime": "2017-06-20 15:51:32",
                            "updatetime": "2017-06-13 11:49:54",
                            "donetime": "2017-06-13 14:22:49",
                            "predict_delivery_time": "2017-06-13 11:39:17",
                            "actual_delivery_time": "2017-06-13 14:16:06"            
                        },
                        {                
                            "id": "3",
                            "number": "OM 3",
                            "description": "公司内网频繁报恶意，怀疑是误报",
                            "status": "2",
                            "type": "3",
                            "close": "1",
                            "refuse": "0",
                            "addtime": "2017-06-20 15:51:32",
                            "updatetime": "2017-06-13 11:49:54",
                            "donetime": "2017-06-13 14:22:49",
                            "predict_delivery_time": "2017-06-13 11:39:17",
                            "actual_delivery_time": "2017-06-13 14:16:06"            
                        },
                        {                
                            "id": "4",
                            "number": "OM 4",
                            "description": "公司内网频繁报恶意，怀疑是误报",
                            "status": "1",
                            "type": "3",
                            "close": "1",
                            "refuse": "0",
                            "addtime": "2017-06-18 15:51:32",
                            "updatetime": "2017-06-13 11:49:54",
                            "donetime": "2017-06-13 14:22:49",
                            "predict_delivery_time": "2017-06-13 11:39:17",
                            "actual_delivery_time": "2017-06-13 14:16:06"            
                        }
                        ,{                
                            "id": "5",
                            "number": "OM 5",
                            "description": "公司内网频繁报恶意，怀疑是误报",
                            "status": "3",
                            "type": "3",
                            "close": "1",
                            "refuse": "0",
                            "addtime": "2017-06-17 15:51:32",
                            "updatetime": "2017-06-13 11:49:54",
                            "donetime": "2017-06-13 14:22:49",
                            "predict_delivery_time": "2017-06-13 11:39:17",
                            "actual_delivery_time": "2017-06-13 14:16:06"            
                        },
                        {                
                            "id": "6",
                            "number": "OM 6",
                            "description": "公司内网频繁报恶意，怀疑是误报",
                            "status": "1",
                            "type": "3",
                            "close": "1",
                            "refuse": "0",
                            "addtime": "2017-06-12 15:51:32",
                            "updatetime": "2017-06-13 11:49:54",
                            "donetime": "2017-06-13 14:22:49",
                            "predict_delivery_time": "2017-06-13 11:39:17",
                            "actual_delivery_time": "2017-06-13 14:16:06"            
                        },
                        {                
                            "id": "7",
                            "number": "OM 7",
                            "description": "公司内网频繁报恶意，怀疑是误报",
                            "status": "2",
                            "type": "3",
                            "close": "1",
                            "refuse": "0",
                            "addtime": "2017-06-12 15:51:32",
                            "updatetime": "2017-06-13 11:49:54",
                            "donetime": "2017-06-13 14:22:49",
                            "predict_delivery_time": "2017-06-13 11:39:17",
                            "actual_delivery_time": "2017-06-13 14:16:06"            
                        },
                        {                
                            "id": "8",
                            "number": "OM 8",
                            "description": "公司内网频繁报恶意，怀疑是误报",
                            "status": "3",
                            "type": "3",
                            "close": "1",
                            "refuse": "0",
                            "addtime": "2017-06-12 15:51:32",
                            "updatetime": "2017-06-13 11:49:54",
                            "donetime": "2017-06-13 14:22:49",
                            "predict_delivery_time": "2017-06-13 11:39:17",
                            "actual_delivery_time": "2017-06-13 14:16:06"            
                        }]    
                    },
                    "errCode":  0,
                    "errInfo":   ""
            }
            
export {testData};